source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/input.conf
source = $HOME/.config/hypr/plugins.conf
source = $HOME/.config/hypr/binds.conf
source = $HOME/.config/hypr/execs.conf

# unscale XWayland
xwayland {
  force_zero_scaling = true
}
env = GDK_SCALE,1
env = XCURSOR_SIZE,12

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 12
    border_size = 2
    col.inactive_border = rgba(45475aee) 45deg
    col.active_border = rgba(1b783caa)
    layout = scrolling

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = true
}


windowrule = match:class cs2, immediate yes
windowrule = match:class steam_app_1422450, immediate yes
windowrule = match:class steam_app_374320, immediate yes


decoration {

    rounding = 15
    blur {
        enabled = true
        size = 3
        passes = 1
    }

}

animations {
    enabled = yes
    animation = specialWorkspace, 1, 5, default, slidefadevert
    animation = windowsOut, 1, 7, default, popin 80%
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

scrolling {
    fullscreen_on_one_column = true
    column_width = 1
    direction = right
}

misc {
    force_default_wallpaper = -1 # Set to 0 to disable the anime mascot wallpapers
}
